[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# Existing redirect for API
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# Redirect old Pen Test pages
[[redirects]]
  from = "/penetration-testing-services"
  to = "/penetration-testing"
  status = 301
  force = true

[[redirects]]
  from = "/penetration-testing-1"
  to = "/penetration-testing"
  status = 301
  force = true

# Fallback for SPA (must come last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
